# Generated by Django 4.1.2 on 2023-03-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occassionalcakes',
            old_name='new_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='weddingcakes',
            old_name='new_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='weddingcakes',
            old_name='old_price',
            new_name='range_price',
        ),
        migrations.RemoveField(
            model_name='occassionalcakes',
            name='old_price',
        ),
    ]
