# Generated by Django 4.1.2 on 2023-01-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='tex2',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='text',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='text3',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='paragrapagh1',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='paragrapagh2',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='paragrapagh3',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
