# Generated by Django 4.1.2 on 2023-01-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_blogs_tex2_alter_blogs_text_alter_blogs_text3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='tex2',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='text3',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='paragrapagh2',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='paragrapagh3',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
    ]
